CREATE TABLE TESTNOTES (ID INT PRIMARY KEY, TITLE VARCHAR(50), CONTENT VARCHAR(500) NOT NULL, CREATED_AT DATE NOT NULL, UPDATED_AT DATE NOT NULL);

INSERT INTO PERSON VALUES(1, 'TestedTitle', 'TestedContent');